/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, {useEffect, useRef} from 'react'
import {useAnimations, useFBX, useGLTF} from '@react-three/drei'
import { asset } from '../utils.js'

const Character = ({ animationName = 'idle', ...props}) => {
    const group = useRef();
    const { nodes, materials } = useGLTF(asset('/models/2B_Maid.glb'))

    const { animations: idleAnimation } = useFBX(asset('/models/animations/idle.fbx'))
    const { animations: waveDanceAnimation } = useFBX(asset('/models/animations/waveDance.fbx'))
    const { animations: snakeDanceAnimation } = useFBX(asset('/models/animations/snakeDance.fbx'))

    if (idleAnimation?.[0]) idleAnimation[0].name = 'idle';
    if (waveDanceAnimation?.[0]) waveDanceAnimation[0].name = 'wave';
    if (snakeDanceAnimation?.[0]) snakeDanceAnimation[0].name = 'snake';

    const { actions } = useAnimations([
        ...(idleAnimation?.[0] ? [idleAnimation[0]] : []),
        ...(waveDanceAnimation?.[0] ? [waveDanceAnimation[0]] : []),
        ...(snakeDanceAnimation?.[0] ? [snakeDanceAnimation[0]] : []),
    ], group);

    useEffect(() => {
        const action = actions?.[animationName];

        if (action) {
            action.reset().fadeIn(0.05).play();
        }

        return () => {
            action?.fadeOut(0.05);
        };
    }, [animationName, actions]);

    return (
        <group {...props} dispose={null} ref={group}>
            <group rotation={[0, 0, 0]}>
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Cabeza'].geometry}
                    material={materials['Cabeza.005']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Cabeza'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Cara'].geometry}
                    material={materials['Cara.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Cara'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Cejas'].geometry}
                    material={materials['Cejas.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Cejas'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Cuerpo'].geometry}
                    material={materials['Cuerpo.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Cuerpo'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Maid_Accesorios_Cuerpo'].geometry}
                    material={materials['Maid_Accesorios_Cuerpo.006']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Maid_Accesorios_Cuerpo'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Maid_Aceesorios_Braso'].geometry}
                    material={materials['Maid_Aceesorios_Braso.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Maid_Aceesorios_Braso'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Mascara'].geometry}
                    material={materials['Mascara.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Mascara'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Muslo_Maid'].geometry}
                    material={materials['Muslo_Maid.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Muslo_Maid'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Pelo'].geometry}
                    material={materials['Pelo.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Pelo'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Piernas'].geometry}
                    material={materials['Piernas.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Piernas'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Talon'].geometry}
                    material={materials['Talon.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Talon'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Tanga'].geometry}
                    material={materials['Tanga.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Tanga'].skeleton}
                />
                <skinnedMesh
                    geometry={nodes['2B_Maid_PORT_BY_DAX_Traje_Maid'].geometry}
                    material={materials['Traje_Maid.004']}
                    skeleton={nodes['2B_Maid_PORT_BY_DAX_Traje_Maid'].skeleton}
                />
                <primitive object={nodes.mixamorigHips} />
            </group>
        </group>
    )
}

useGLTF.preload(asset('/models/2B_Maid.glb'))

export default Character;
